# docker-compose.yml
version: '3.8'
services:
 # Application
  app:
      build:
          context: .
          dockerfile: app.dockerfile
      working_dir: /var/www
      environment:
        REDIS_URL: redis://redis:6379
      volumes:
          - ./:/var/www
      depends_on:
          - "db"
    # Web Server
  web:
        build:
            context: .
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "app"
        ports:
            - 80:80 
  node:
        build:
            context: .
            dockerfile: node.dockerfile
        working_dir: /app
        volumes:
            - ./:/var/www
        depends_on:
            - "app"
        ports:
            - 3000:3000 

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgAdmin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db 
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: kashan1dev@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: password 
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped